-- MySQL Script generated by MySQL Workbench
-- Fri Nov 16 21:53:47 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_tp_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_tp_usuario` (
  `id_tp_us` INT NOT NULL,
  `nm_tp_us` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tp_us`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_psc_jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_psc_jogador` (
  `id_posicao_jogador` INT NOT NULL AUTO_INCREMENT,
  `tb_nm_posicao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_posicao_jogador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_usuario` (
  `idUsuario` INT NOT NULL,
  `nm_us` VARCHAR(45) NOT NULL,
  `senha_us` VARCHAR(8) NOT NULL,
  `email_us` VARCHAR(20) NOT NULL,
  `telefone` VARCHAR(14) NULL,
  `tb_tp_usuario_id_tp_us` INT NOT NULL,
  `tb_psc_jogador_id_posicao_jogador` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `email_us_UNIQUE` (`email_us` ASC) VISIBLE,
  INDEX `fk_tb_usuario_tb_tp_usuario1_idx` (`tb_tp_usuario_id_tp_us` ASC) VISIBLE,
  INDEX `fk_tb_usuario_tb_psc_jogador1_idx` (`tb_psc_jogador_id_posicao_jogador` ASC) VISIBLE,
  CONSTRAINT `fk_tb_usuario_tb_tp_usuario1`
    FOREIGN KEY (`tb_tp_usuario_id_tp_us`)
    REFERENCES `mydb`.`tb_tp_usuario` (`id_tp_us`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_usuario_tb_psc_jogador1`
    FOREIGN KEY (`tb_psc_jogador_id_posicao_jogador`)
    REFERENCES `mydb`.`tb_psc_jogador` (`id_posicao_jogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_endereco` (
  `id_tb_endereco` INT NOT NULL,
  `cidade` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tb_endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_estabelecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_estabelecimento` (
  `id_tb_estabelecimento` INT NOT NULL,
  `nome_estabelecimento` VARCHAR(45) NULL,
  `tb_usuario_idUsuario` INT NOT NULL,
  `tb_endereco_id_tb_endereco` INT NOT NULL,
  PRIMARY KEY (`id_tb_estabelecimento`, `tb_usuario_idUsuario`, `tb_endereco_id_tb_endereco`),
  INDEX `fk_tb_estabelecimento_tb_usuario1_idx` (`tb_usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_tb_estabelecimento_tb_endereco1_idx` (`tb_endereco_id_tb_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_tb_estabelecimento_tb_usuario1`
    FOREIGN KEY (`tb_usuario_idUsuario`)
    REFERENCES `mydb`.`tb_usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_estabelecimento_tb_endereco1`
    FOREIGN KEY (`tb_endereco_id_tb_endereco`)
    REFERENCES `mydb`.`tb_endereco` (`id_tb_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_campo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_campo` (
  `id_Campo` INT ZEROFILL NOT NULL,
  `nomeQuadra` VARCHAR(45) NOT NULL,
  `tb_estabelecimento_id_tb_estabelecimento` INT NOT NULL,
  `tb_estabelecimento_tb_usuario_idUsuario` INT NOT NULL,
  `tb_estabelecimento_tb_endereco_id_tb_endereco` INT NOT NULL,
  PRIMARY KEY (`id_Campo`),
  INDEX `fk_tb_campo_tb_estabelecimento1_idx` (`tb_estabelecimento_id_tb_estabelecimento` ASC, `tb_estabelecimento_tb_usuario_idUsuario` ASC, `tb_estabelecimento_tb_endereco_id_tb_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_tb_campo_tb_estabelecimento1`
    FOREIGN KEY (`tb_estabelecimento_id_tb_estabelecimento` , `tb_estabelecimento_tb_usuario_idUsuario` , `tb_estabelecimento_tb_endereco_id_tb_endereco`)
    REFERENCES `mydb`.`tb_estabelecimento` (`id_tb_estabelecimento` , `tb_usuario_idUsuario` , `tb_endereco_id_tb_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jogador_has_reservar_quadra_has_Quadra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Jogador_has_reservar_quadra_has_Quadra` (
  `Jogador_has_reservar_quadra_Jogador_idJogador` INT NOT NULL,
  `Jogador_has_reservar_quadra_reservar_quadra_Quadra_idQuadra` INT NOT NULL,
  `Quadra_idQuadra` INT NOT NULL,
  PRIMARY KEY (`Jogador_has_reservar_quadra_Jogador_idJogador`, `Jogador_has_reservar_quadra_reservar_quadra_Quadra_idQuadra`, `Quadra_idQuadra`),
  INDEX `fk_Jogador_has_reservar_quadra_has_Quadra_Quadra1_idx` (`Quadra_idQuadra` ASC) VISIBLE,
  CONSTRAINT `fk_Jogador_has_reservar_quadra_has_Quadra_Quadra1`
    FOREIGN KEY (`Quadra_idQuadra`)
    REFERENCES `mydb`.`tb_campo` (`id_Campo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_time` (
  `id_time` INT NOT NULL AUTO_INCREMENT,
  `nm_time` VARCHAR(45) NULL,
  `tb_usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`id_time`),
  INDEX `fk_tb_time_tb_usuario1_idx` (`tb_usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_time_tb_usuario1`
    FOREIGN KEY (`tb_usuario_idUsuario`)
    REFERENCES `mydb`.`tb_usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_reserva` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `tb_campo_id_Campo` INT ZEROFILL NOT NULL,
  `tmp_reserva` VARCHAR(45) NULL,
  `vl_total_reserva` DECIMAL NULL,
  PRIMARY KEY (`id_reserva`),
  INDEX `fk_tb_reserva_tb_campo1_idx` (`tb_campo_id_Campo` ASC) VISIBLE,
  CONSTRAINT `fk_tb_reserva_tb_campo1`
    FOREIGN KEY (`tb_campo_id_Campo`)
    REFERENCES `mydb`.`tb_campo` (`id_Campo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
